# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VoxArtist(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, id: str=None, ts_added: int=None, ts_modified: int=None):  # noqa: E501
        """VoxArtist - a model defined in Swagger

        :param name: The name of this VoxArtist.  # noqa: E501
        :type name: str
        :param id: The id of this VoxArtist.  # noqa: E501
        :type id: str
        :param ts_added: The ts_added of this VoxArtist.  # noqa: E501
        :type ts_added: int
        :param ts_modified: The ts_modified of this VoxArtist.  # noqa: E501
        :type ts_modified: int
        """
        self.swagger_types = {
            'name': str,
            'id': str,
            'ts_added': int,
            'ts_modified': int
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'ts_added': 'ts_added',
            'ts_modified': 'ts_modified'
        }
        self._name = name
        self._id = id
        self._ts_added = ts_added
        self._ts_modified = ts_modified

    @classmethod
    def from_dict(cls, dikt) -> 'VoxArtist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VoxArtist of this VoxArtist.  # noqa: E501
        :rtype: VoxArtist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this VoxArtist.


        :return: The name of this VoxArtist.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VoxArtist.


        :param name: The name of this VoxArtist.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def id(self) -> str:
        """Gets the id of this VoxArtist.


        :return: The id of this VoxArtist.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this VoxArtist.


        :param id: The id of this VoxArtist.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def ts_added(self) -> int:
        """Gets the ts_added of this VoxArtist.


        :return: The ts_added of this VoxArtist.
        :rtype: int
        """
        return self._ts_added

    @ts_added.setter
    def ts_added(self, ts_added: int):
        """Sets the ts_added of this VoxArtist.


        :param ts_added: The ts_added of this VoxArtist.
        :type ts_added: int
        """

        self._ts_added = ts_added

    @property
    def ts_modified(self) -> int:
        """Gets the ts_modified of this VoxArtist.


        :return: The ts_modified of this VoxArtist.
        :rtype: int
        """
        return self._ts_modified

    @ts_modified.setter
    def ts_modified(self, ts_modified: int):
        """Sets the ts_modified of this VoxArtist.


        :param ts_modified: The ts_modified of this VoxArtist.
        :type ts_modified: int
        """

        self._ts_modified = ts_modified
