swagger: "2.0"
info:
  version: "1.0.0"
  title: "VOX Cloud Proxy"
basePath: "/api/v1"
tags:
  - name: "vox"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /status:
    get:
      tags:
        - "vox"
      summary: "Status of VOX Proxy"
      operationId: "status"
      responses:
        200:
          description: "Status of VOX Proxy."

  /library/build:
    post:      
      tags:
        - "vox"
      summary: "Build an in-memory VOX Library"
      operationId: "library_build"
      parameters:
        - name: "library_creation"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/VoxLibraryCreation"
      responses:
        200:
          description: "Build an in-memory VOX Library"
          schema:
            $ref: '#/definitions/VoxLibraryDetails'

  /library/artists:
    get:      
      tags:
        - "vox"
      summary: "Get artists from VOX Lbrary"
      operationId: "get_artists"
      parameters:
        - name: sort_by
          in: query
          required: true
          description: sort by name or latest.
          enum:
            - "name" 
            - "latest"
          type: string
        - name: limit
          in: query
          required: true
          description: limit number of items returned
          type: integer
        - name: ascending
          in: query
          required: true
          description: ascending
          type: boolean          
      responses:
        200:
          description: "Artists from VOX Lbrary"
          schema:
            $ref: '#/definitions/VoxArtists'

  # /library/artists/{id}:
  #   get:      
  #     tags:
  #       - "vox"
  #     summary: "Get single artist from VOX Lbrary, by id"
  #     operationId: "get_artist_by_id"
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         description: The VOX artist id.
  #         type: string
  #     responses:
  #       200:
  #         description: "Artist from VOX Lbrary"
  #         schema:
  #           $ref: '#/definitions/VoxArtist'

  /library/artists/{artist_id}/albums:
    get:      
      tags:
        - "vox"
      summary: "Get albums from artist from VOX Lbrary, by artist id"
      operationId: "get_artist_albums"
      parameters:
        - name: artist_id
          in: path
          required: true
          description: The VOX artist id.
          type: string
        - name: sort_by
          in: query
          required: true
          description: sort by name or latest.
          enum:
            - "name" 
            - "latest"
            - year
          type: string
        - name: limit
          in: query
          required: true
          description: limit number of items returned
          type: integer
        - name: ascending
          in: query
          required: true
          description: ascending
          type: boolean          
      responses:
        200:
          description: "Albums by artist from VOX Lbrary"
          schema:
            $ref: '#/definitions/VoxAlbums'

  /library/albums/{id}:
    get:      
      tags:
        - "vox"
      summary: "Get single album from VOX Lbrary, by id"
      operationId: "get_album_by_id"
      parameters:
        - name: id
          in: path
          required: true
          description: The VOX album id.
          type: string
      responses:
        200:
          description: "Album from VOX Lbrary"
          schema:
            $ref: '#/definitions/VoxAlbum'

  /library/albums/{album_id}/tracks:
    get:      
      tags:
        - "vox"
      summary: "Get tracks from VOX Lbrary, by album id"
      operationId: "get_tracks_by_album"
      parameters:
        - name: album_id
          in: path
          required: true
          description: The VOX album id.
          type: string
      responses:
        200:
          description: "Tracks from VOX Album"
          schema:
            $ref: '#/definitions/VoxTracks'


  /login/{method}:
    post:
      tags:
        - "vox"
      summary: "Login"
      operationId: "login"
      parameters:
        - name: "method"
          in: "path"
          description: "The login method.  Only facebook is supported for now."
          required: true
          type: "string"
        - name: "user"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: "Logged in."
          
definitions:
  User:
    type: "object"
    required:
      - "email"
      - "password"
    properties:
      email:
        type: "string"
      password:
        type: "string"

  VoxLibraryCreation:
    type: "object"
    properties:
      type:
        type: "string"

  VoxLibraryDetails:
    type: "object"
    required:
      - "tracks_count"
      - "size"
      - "size_human"
      - "artists_count"
    properties:
      size_human:
        type: string
      tracks_count:
        type: integer
      artists_count:
        type: integer
      albums_count:
        type: integer
      size:
        type: integer

  VoxArtist:
    type: "object"
    required:
      - "name"
      - "id"
    properties:
      name:
        type: "string"
      id:
        type: "string"
      ts_added:
        type: integer
      ts_modified:
        type: integer

  VoxAlbum:
    type: "object"
    required:
      - "name"
      - "id"
    properties:
      name:
        type: "string"
      id:
        type: "string"
      release_year:
        type: integer
      tracks_count:
        type: integer       
      format:
        type: string 
      ts_added:
        type: integer
      ts_modified:
        type: integer

  VoxTrack:
    type: "object"
    required:
      - "name"
      - "id"
    properties:
      name:
        type: "string"
      album_artist_name:
        type: string
      album_id:
        type: string
      album_name:
        type: string
      artist_name:
        type: string
      bitrate:
        type: integer
      date_added:
        type: integer
      disc_number:
        type: integer
      disc_total: 
        type: integer
      file_item_data_sha1:
        type: string
      file_item_ext:
        type: string
      file_item_id:
        type: string
      file_item_sha1:
        type: string
      file_item_size:
        type: integer
      id:
        type: string
      genre:
        type: string
      release_year:
        type: integer
      sample_rate:
        type: integer
      track_number:
        type: integer

  VoxArtists:
    type: array
    items:
      $ref: '#/definitions/VoxArtist'

  VoxAlbums:
    type: array
    items:
      $ref: '#/definitions/VoxAlbum'

  VoxTracks:
    type: array
    items:
      $ref: '#/definitions/VoxTrack'